---
abstract: 'Alien module for Capstone Engine from www.capstone-engine.org'
author:
  - 'Vikas N. Kumar <vikas@cpan.org>'
build_requires:
  Alien::Base::ModuleBuild: '0.029'
  Alien::gmake: '0.11'
  Module::Build: '0'
  Test2: '0'
  Test::Alien: '0'
configure_requires:
  Alien::Base::ModuleBuild: '0.029'
  Module::Build: '0'
  Pod::Readme: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Capstone
provides:
  Alien::Capstone:
    file: lib/Alien/Capstone.pm
    version: '0.05'
requires:
  Alien::Base: '0.029'
  File::ShareDir: '1.00'
resources:
  bugtracker: https://github.com/selectiveintellect/p5-alien-capstone/issues
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/selectiveintellect/p5-alien-capstone
version: '0.05'
